[package]
name = "kfsend"
version = "0.1.0"
authors = ["<psydebug>"]
edition = "2018"

[dependencies]
kafka = "0.8"
uuid = { version = "0.8", features = ["v4"] }
config = "0.10"
serde_derive = "^1.0.8"
serde = "^1.0.8"