# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: registry.access.redhat.com/devtools/rust-toolset-rhel7:latest
    steps:
      - checkout
      - run: curl https://github.com/rust-lang/crates.io-index
      - run:
          name: Cargo Build 
          command: cargo build --release -v
          environment:
            CARGO_NET_GIT_FETCH_WITH_CLI=true


      
